#!/usr/bin/env python
import os, sys

#Check if root user is used
if os.geteuid() != 0:
  print('ERROR: Thist script must be run with root privileges!\nUse sudo in front of the command.')
  sys.exit(1)

easyrsaPath = "/etc/openvpn/easy-rsa/"
ovpnfilesPath = "/var/www/ovpnfiles"
username = raw_input("Type the username: ")
usermail = raw_input("Leave blank if you don`t want to send the configuration file via e-mail.\nType the e-mail address: ")

#Generate Keys
genKeys = os.system("cd "+easyrsaPath+"; source ./vars; ./pkitool "+username)
#Generate ovpn file
ovpnf=open(ovpnfilesPath+"keys/"+username+".ovpn","w+")
caf=open(easyrsaPath+"keys/ca.crt","r")
crtf=open(easyrsaPath+"keys/"+username+".crt","r")
keyf=open(easyrsaPath+"keys/"+username+".key","r")
writeline=0
config='''client
dev tun
proto tcp-client
remote vpn.adrianstoica.de 1194
resolv-retry infinite
nobind
persist-key
persist-tun
mute-replay-warnings
cipher AES-256-CBC
ns-cert-type server
comp-lzo adaptive
redirect-gateway def1
'''
ovpnf.write(config)
ovpnf.close()
ovpnf=open(ovpnfilesPath+"keys/"+username+".ovpn","a")
for line in caf:
  if "BEGIN CERTIFICATE" in line:
    writeline=1
    ovpnf.write("<ca>\n")
  if writeline==1:
    ovpnf.write(line)
  if "END CERTIFICATE" in line:
    writeline=0
    ovpnf.write("</ca>\n")
    break
for line in crtf:
  if "BEGIN CERTIFICATE" in line:
    writeline=1
    ovpnf.write("<cert>\n")
  if writeline==1:
    ovpnf.write(line)
  if "END CERTIFICATE" in line:
    writeline=0
    ovpnf.write("</cert>\n")
    break
for line in keyf:
  if "BEGIN PRIVATE KEY" in line:
    writeline=1
    ovpnf.write("<key>\n")
  if writeline==1:
    ovpnf.write(line)
  if "END PRIVATE KEY" in line:
    writeline=0
    ovpnf.write("</key>\n")
    break
ovpnf.close()
#send config file via email
if usermail != '':
  os.system('mail -a /var/www/ovpnfiles/'+username+'.ovpn -s  "'+username+' OVPN Config file" -r noreply@adrianstoica.de '+usermail+' < /dev/null')